// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_logo
void ui_logo_screen_init(void);
void ui_event_logo(lv_event_t * e);
lv_obj_t * ui_logo;
lv_obj_t * ui_Image1;


// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
lv_obj_t * ui_HOME;
void ui_event_WIFIBUTTON(lv_event_t * e);
lv_obj_t * ui_WIFIBUTTON;
void ui_event_RFIDBUTTON(lv_event_t * e);
lv_obj_t * ui_RFIDBUTTON;
lv_obj_t * ui_WIFILABEL;
lv_obj_t * ui_RFIDLABEL;


// SCREEN: ui_RFIDSCREEN
void ui_RFIDSCREEN_screen_init(void);
lv_obj_t * ui_RFIDSCREEN;
lv_obj_t * ui_RFIDINSTRUCT;
void ui_event_RFIDSCREENBACKBUTTON(lv_event_t * e);
lv_obj_t * ui_RFIDSCREENBACKBUTTON;
lv_obj_t * ui_RFIDSCREENBACKLABEL;


// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
void ui_event_WiFiScreen(lv_event_t * e);
lv_obj_t * ui_WiFiScreen;
lv_obj_t * ui_WiFi_Title;
lv_obj_t * ui_SSIDLABEL;
lv_obj_t * ui_PWDLABEL;
void ui_event_SSID_BOX(lv_event_t * e);
lv_obj_t * ui_SSID_BOX;
void ui_event_PWDBOX(lv_event_t * e);
lv_obj_t * ui_PWDBOX;
void ui_event_DONEBUTTON(lv_event_t * e);
lv_obj_t * ui_DONEBUTTON;
void ui_event_BACKBUTTON(lv_event_t * e);
lv_obj_t * ui_BACKBUTTON;
lv_obj_t * ui_DONELABEL;
lv_obj_t * ui_BACKLABELWIFI;
lv_obj_t * ui_ACKNOWLEDGEMENT;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_logo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_HOME_screen_init);
    }
}
void ui_event_WIFIBUTTON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFiScreen_screen_init);
    }
}
void ui_event_RFIDBUTTON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RFIDSCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RFIDSCREEN_screen_init);
    }
}



void ui_event_SSID_BOX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_SSID_BOX);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PWDBOX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PWDBOX);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_BACKBUTTON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HOME_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_logo_screen_init();
    ui_HOME_screen_init();
    ui_RFIDSCREEN_screen_init();
    ui_WiFiScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_logo);
}
