// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#ifndef _SECURITY_SYSTEM_OS_UI_H
#define _SECURITY_SYSTEM_OS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_logo
void ui_logo_screen_init(void);
void ui_event_logo(lv_event_t * e);
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
extern lv_obj_t * ui_HOME;
void ui_event_WIFIBUTTON(lv_event_t * e);
extern lv_obj_t * ui_WIFIBUTTON;
void ui_event_RFIDBUTTON(lv_event_t * e);
extern lv_obj_t * ui_RFIDBUTTON;
extern lv_obj_t * ui_WIFILABEL;
extern lv_obj_t * ui_RFIDLABEL;
// SCREEN: ui_RFIDSCREEN
void ui_RFIDSCREEN_screen_init(void);
void ui_event_RFIDSCREEN(lv_event_t * e);
extern lv_obj_t * ui_RFIDSCREEN;
extern lv_obj_t * ui_RFIDINSTRUCT;
void ui_event_RFIDSCREENBACKBUTTON(lv_event_t * e);
extern lv_obj_t * ui_RFIDSCREENBACKBUTTON;
extern lv_obj_t * ui_RFIDSCREENBACKLABEL;
// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
void ui_event_WiFiScreen(lv_event_t * e);
extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_WiFi_Title;
extern lv_obj_t * ui_SSIDLABEL;
extern lv_obj_t * ui_PWDLABEL;
void ui_event_SSID_BOX(lv_event_t * e);
extern lv_obj_t * ui_SSID_BOX;
void ui_event_PWDBOX(lv_event_t * e);
extern lv_obj_t * ui_PWDBOX;
void ui_event_DONEBUTTON(lv_event_t * e);
extern lv_obj_t * ui_DONEBUTTON;
void ui_event_BACKBUTTON(lv_event_t * e);
extern lv_obj_t * ui_BACKBUTTON;
extern lv_obj_t * ui_DONELABEL;
extern lv_obj_t * ui_BACKLABELWIFI;
extern lv_obj_t * ui_ACKNOWLEDGEMENT;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_828054267);    // assets/Core X(transparent).png



LV_FONT_DECLARE(ui_font_MON10);
LV_FONT_DECLARE(ui_font_MON18);
LV_FONT_DECLARE(ui_font_MON20);
LV_FONT_DECLARE(ui_font_MON36);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
