// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"


bool rfid_activate(lv_event_t * e)
{
	
}

void rfid_decativate(lv_event_t * e)
{
	// Your code here
}

void credChange(lv_event_t * e)
{
	// Your code here
}
