// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WIFIBUTTON = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_WIFIBUTTON, 396);
    lv_obj_set_height(ui_WIFIBUTTON, 72);
    lv_obj_set_x(ui_WIFIBUTTON, 10);
    lv_obj_set_y(ui_WIFIBUTTON, 69);
    lv_obj_set_align(ui_WIFIBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_WIFIBUTTON, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WIFIBUTTON, lv_color_hex(0x8BCEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDBUTTON = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_RFIDBUTTON, 396);
    lv_obj_set_height(ui_RFIDBUTTON, 72);
    lv_obj_set_x(ui_RFIDBUTTON, 5);
    lv_obj_set_y(ui_RFIDBUTTON, -71);
    lv_obj_set_align(ui_RFIDBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RFIDBUTTON, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RFIDBUTTON, lv_color_hex(0x8BCEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RFIDBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFILABEL = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_WIFILABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFILABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFILABEL, 1);
    lv_obj_set_y(ui_WIFILABEL, 70);
    lv_obj_set_align(ui_WIFILABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFILABEL, "WIFI SETTINGS");
    lv_obj_set_style_text_color(ui_WIFILABEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFILABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WIFILABEL, &ui_font_MON36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDLABEL = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_RFIDLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFIDLABEL, 2);
    lv_obj_set_y(ui_RFIDLABEL, -72);
    lv_obj_set_align(ui_RFIDLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDLABEL, "START");
    lv_obj_set_style_text_color(ui_RFIDLABEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFIDLABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RFIDLABEL, &ui_font_MON36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WIFIBUTTON, ui_event_WIFIBUTTON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RFIDBUTTON, ui_event_RFIDBUTTON, LV_EVENT_ALL, NULL);

}
