// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"

void ui_logo_screen_init(void)
{
    ui_logo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_logo);
    lv_img_set_src(ui_Image1, &ui_img_828054267);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 257
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_logo, ui_event_logo, LV_EVENT_ALL, NULL);

}
