// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"

void ui_RFIDSCREEN_screen_init(void)
{
    ui_RFIDSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RFIDSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RFIDINSTRUCT = lv_label_create(ui_RFIDSCREEN);
    lv_obj_set_width(ui_RFIDINSTRUCT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDINSTRUCT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFIDINSTRUCT, 5);
    lv_obj_set_y(ui_RFIDINSTRUCT, -26);
    lv_obj_set_align(ui_RFIDINSTRUCT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDINSTRUCT, "SCAN YOUR CARD\nOR RFID TAG");
    lv_obj_set_style_text_align(ui_RFIDINSTRUCT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RFIDINSTRUCT, &ui_font_MON36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDSCREENBACKBUTTON = lv_btn_create(ui_RFIDSCREEN);
    lv_obj_set_width(ui_RFIDSCREENBACKBUTTON, 100);
    lv_obj_set_height(ui_RFIDSCREENBACKBUTTON, 50);
    lv_obj_set_x(ui_RFIDSCREENBACKBUTTON, 6);
    lv_obj_set_y(ui_RFIDSCREENBACKBUTTON, 73);
    lv_obj_set_align(ui_RFIDSCREENBACKBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RFIDSCREENBACKBUTTON, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RFIDSCREENBACKBUTTON, lv_color_hex(0x8BCEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RFIDSCREENBACKBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDSCREENBACKLABEL = lv_label_create(ui_RFIDSCREEN);
    lv_obj_set_width(ui_RFIDSCREENBACKLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDSCREENBACKLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFIDSCREENBACKLABEL, 4);
    lv_obj_set_y(ui_RFIDSCREENBACKLABEL, 73);
    lv_obj_set_align(ui_RFIDSCREENBACKLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDSCREENBACKLABEL, "BACK");
    lv_obj_set_style_text_color(ui_RFIDSCREENBACKLABEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFIDSCREENBACKLABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RFIDSCREENBACKLABEL, &ui_font_MON18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RFIDSCREENBACKBUTTON, ui_event_RFIDSCREENBACKBUTTON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RFIDSCREEN, ui_event_RFIDSCREEN, LV_EVENT_ALL, NULL);

}
