// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Security System OS

#include "ui.h"

void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFi_Title = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_WiFi_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi_Title, -3);
    lv_obj_set_y(ui_WiFi_Title, -131);
    lv_obj_set_align(ui_WiFi_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi_Title, "WIFI SETTINGS");
    lv_obj_set_style_text_font(ui_WiFi_Title, &ui_font_MON36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLABEL = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_SSIDLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDLABEL, -189);
    lv_obj_set_y(ui_SSIDLABEL, -68);
    lv_obj_set_align(ui_SSIDLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLABEL, "SSID :");
    lv_obj_set_style_text_font(ui_SSIDLABEL, &ui_font_MON18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWDLABEL = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PWDLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWDLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWDLABEL, -188);
    lv_obj_set_y(ui_PWDLABEL, -9);
    lv_obj_set_align(ui_PWDLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWDLABEL, "KEY :");
    lv_obj_set_style_text_font(ui_PWDLABEL, &ui_font_MON18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSID_BOX = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_SSID_BOX, 349);
    lv_obj_set_height(ui_SSID_BOX, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_SSID_BOX, 30);
    lv_obj_set_y(ui_SSID_BOX, -70);
    lv_obj_set_align(ui_SSID_BOX, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSID_BOX, "SSID");
    lv_textarea_set_one_line(ui_SSID_BOX, true);



    ui_PWDBOX = lv_textarea_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PWDBOX, 348);
    lv_obj_set_height(ui_PWDBOX, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_PWDBOX, 28);
    lv_obj_set_y(ui_PWDBOX, -12);
    lv_obj_set_align(ui_PWDBOX, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PWDBOX, "PASSWORD");
    lv_textarea_set_one_line(ui_PWDBOX, true);



    ui_DONEBUTTON = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_DONEBUTTON, 100);
    lv_obj_set_height(ui_DONEBUTTON, 50);
    lv_obj_set_x(ui_DONEBUTTON, -92);
    lv_obj_set_y(ui_DONEBUTTON, 107);
    lv_obj_set_align(ui_DONEBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_DONEBUTTON, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DONEBUTTON, lv_color_hex(0x8BCEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DONEBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKBUTTON = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_BACKBUTTON, 100);
    lv_obj_set_height(ui_BACKBUTTON, 50);
    lv_obj_set_x(ui_BACKBUTTON, 85);
    lv_obj_set_y(ui_BACKBUTTON, 106);
    lv_obj_set_align(ui_BACKBUTTON, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BACKBUTTON, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKBUTTON, lv_color_hex(0x8BCEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DONELABEL = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_DONELABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DONELABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DONELABEL, -92);
    lv_obj_set_y(ui_DONELABEL, 107);
    lv_obj_set_align(ui_DONELABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DONELABEL, "DONE");
    lv_obj_set_style_text_color(ui_DONELABEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DONELABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DONELABEL, &ui_font_MON18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKLABELWIFI = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_BACKLABELWIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BACKLABELWIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BACKLABELWIFI, 86);
    lv_obj_set_y(ui_BACKLABELWIFI, 106);
    lv_obj_set_align(ui_BACKLABELWIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BACKLABELWIFI, "BACK");
    lv_obj_set_style_text_color(ui_BACKLABELWIFI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKLABELWIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BACKLABELWIFI, &ui_font_MON18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACKNOWLEDGEMENT = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_ACKNOWLEDGEMENT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACKNOWLEDGEMENT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACKNOWLEDGEMENT, -3);
    lv_obj_set_y(ui_ACKNOWLEDGEMENT, 46);
    lv_obj_set_align(ui_ACKNOWLEDGEMENT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ACKNOWLEDGEMENT, "");
    lv_obj_set_style_text_color(ui_ACKNOWLEDGEMENT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ACKNOWLEDGEMENT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ACKNOWLEDGEMENT, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ACKNOWLEDGEMENT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ACKNOWLEDGEMENT, &ui_font_MON10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_WiFiScreen);
    lv_obj_set_width(ui_Keyboard1, 480);
    lv_obj_set_height(ui_Keyboard1, 170);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags

    lv_obj_add_event_cb(ui_SSID_BOX, ui_event_SSID_BOX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWDBOX, ui_event_PWDBOX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DONEBUTTON, ui_event_DONEBUTTON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACKBUTTON, ui_event_BACKBUTTON, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_SSID_BOX);
    lv_obj_add_event_cb(ui_WiFiScreen, ui_event_WiFiScreen, LV_EVENT_ALL, NULL);

}
